### ISSUE TITLE
Confirmation of the QSO

### ISSUE THREAD

**Issue by Wi5eJ4rl** [manuelkasper/sotlas-frontend#21]
Hello,

Every time I have a QSO i try to check if activator logged me. You know, sometimes QSO is really hard and I not sure that it was everything ok.

If there would appear some kind of star or tick next to the "My chases" positions it will be very nice. I think everybody will have more fun with this.

What do you think? It is possible to add such as this feature?

73

**Comment by manuelkasper** [comment]
Hello! What you are describing sounds exactly like a feature that once was present in the SOTA database, but got removed because people deliberately modified their logs to get the "asterisk" if the other party made a mistake logging them. See the discussion at https://reflector.sota.org.uk/t/the-chaser-confirmation-asterisk/14166

So it's unlikely to be added to SOTLAS.

**Comment by manuelkasper** [comment]
Hello! What you are describing sounds exactly like a feature that once was present in the SOTA database, but got removed because people deliberately modified their logs to get the "asterisk" if the other party made a mistake logging them. See the discussion at https://reflector.sota.org.uk/t/the-chaser-confirmation-asterisk/14166

So it's unlikely to be added to SOTLAS.
